[kakaotv_preview]
title = "우리 영화 볼래?"
url = "https://tv.kakao.com/channel/462787/video"
entrySelector = "ul[class='list_vertical'] li"
titleSelector = "strong[class='tit_item']"
linkSelector = "a[class='link_contents']"
contentSelector = "span[class='mark_play']"
imageSelector = "img[class='thumb_img']"
waitUntil = "networkidle"

[kakaotv_netflix]
title = "카카오TV ─ 넷플릭스"
url = "https://tv.kakao.com/channel/3220576/video"
entrySelector = "ul[class='list_vertical'] li"
titleSelector = "strong[class='tit_item']"
linkSelector = "a[class='link_contents']"
contentSelector = "span[class='mark_play']"
imageSelector = "img[class='thumb_img']"
waitUntil = "networkidle"

[navertv_moviepreview]
title = "네이버 영화 예고편 저장소"
url = "https://tv.naver.com/navermovie/clips"
entrySelector = "div div[class^='cds _MM_CARD']"
titleSelector = "dt[class='title'] > a > tooltip"
linkSelector = "dt[class='title'] a"
imageSelector = "div[class='cds_type'] a img"
contentSelector = "span[class='time']"